enable-module-update = true
parallel-jobs = 1

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/andrews-apks/apks/com.google.android.youtube"

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/andrews-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
app-name = "Reddit"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
clone = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/andrews-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"

[Twitter-Piko]
app-name = "Twitter"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
build-mode = "module"
version = "11.81.0-release.0"
include-stock = "split"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/andrews-apks/apks/com.twitter.android"
excluded-patches = "'Block redirecting to X Lite'"

[Instagram-Piko]
app-name = "Instagram"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
build-mode = "both"
clone = true
version = "430.0.0.53.80"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/andrews-apks/apks/com.instagram.android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"

[Facebook-DeVanced]
app-name = "Facebook"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "De-Vanced"
build-mode = "both"
clone = true
version = "490.0.0.63.82"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/andrews-apks/apks/com.facebook.katana"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"

[Threads-DeVanced]
app-name = "Threads"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "De-Vanced"
build-mode = "both"
clone = true
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/andrews-apks/apks/com.instagram.barcelona"
apkmirror-dlurl = "https://www.apkmirror.com/apk/meta-platforms-inc/threads-instagram/"
uptodown-dlurl = "https://threads.en.uptodown.com/android"

[Telegram-Paresh]
app-name = "Telegram"
patches-source = "gitlab:Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Paresh"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram/"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/andrews-apks/apks/org.telegram.messenger.web"

[Photos-DeVanced]
app-name = "Photos"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "De-Vanced"
build-mode = "both"
clone = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/andrews-apks/apks/com.google.android.apps.photos"
